[project]
name = "cryptopulse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-core>=1.11",
    "dbt-duckdb>=1.10.1",
    "duckdb>=1.5.2",
    "httpx>=0.28.1",
    "pandas>=3.0.2",
    "pyarrow>=24.0.0",
    "pydantic>=2.13.3",
    "pytz>=2026.1.post1",
    "streamlit>=1.57.0",
    "tzdata>=2026.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.12",
]
